platform :ios, "5.0"

#正式版 经过测试后上线的稳定版本
#pod 'AVOSCloud'
#pod 'AVOSCloudSNS'

#测试版 可以随时更新最新版的SDK(但是不能保证稳定)
pod 'AVOSCloud', :podspec => 'https://download.avoscloud.com/sdk/iOS/release-beta/AVOSCloud.podspec'
pod 'AVOSCloudSNS', :podspec => 'https://download.avoscloud.com/sdk/iOS/release-beta/AVOSCloudSNS.podspec'
